pulse.rules = [
    {
        matches = [
            { application.process.binary = "slack" }
            { application.process.binary = "chromium-browser" }
        ]
        actions = { quirks = [ block-source-volume ] }
    }
]
